### ISSUE TITLE
IRC bot doesn't react when told "help"

### ISSUE THREAD

**Issue by bnjbvr** [mrgiggles/histoire#28]
It seems that if the message contains "help", the notification isn't registered by the bot, for some reason. (I guess it's intercepted by another handler that would provide help, although it doesn't send any private message or anything like this)

@hotsphink Can you have a look please? Thanks!

(Also, random question: would it make sense to also open-source the code of the bot itself, making sure to hide credentials etc.?)

**Comment by hotsphink** [comment]
Yes, I can take a look. Though this issue belongs at https://bitbucket.org/sfink/mrgiggles -- the mrgiggles.py script creates 3 connections to the IRC channel with 3 different nicks (mrgiggles, confession, and standups- -- though nobody is using standups- anymore, so I could probably remove that from the configuration file.) They process their input a little differently, though, and I'm not surprised at a bug like this. (The confession bot mostly just passes everything through, but does attempt to respond to help requests. Badly.)

So yes, the source for the bot is open and available. I think fitzgen is the only one who's ever patched it so far, though. But it would be great to have more people hacking on it. One warning -- I will probably be wrapping it in a Rust binary that runs the python interpreter soon, because I have some Rust code that I want to expose to the bot. But I don't think that should invalidate patches to the python. Further out, I'm hoping to move from used Twisted to native python3 async stuff, which would be a pretty big rewrite.

**Comment by hotsphink** [comment]
Moved to https://bitbucket.org/sfink/mrgiggles/issues/1/confession-irc-bot-doesnt-react-when-told
